field: d1bbbf2d-54b0-4856-bf6e-2baa75df92e7 # Awards
fieldLayouts:
  87a96b01-9517-476c-9b88-4ce9f7ca3d0d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e54ec981-fe8b-427f-b328-10616332374a # Award Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 506089a1-5b7d-4a8f-879c-dfd8bd0778b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d21afcfd-1229-4970-a1e4-e4565854c097
        userCondition: null
fields:
  e54ec981-fe8b-427f-b328-10616332374a: # Award Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: awardImage
    instructions: 'Upload square (1:1) image'
    name: 'Award Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: award
name: Award
sortOrder: 1
