field: e5149c70-e0c4-4cfb-9617-9afd96b792c5 # Proud to Support
fieldLayouts:
  af647de7-20da-43da-ab10-a9b3b5f804cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3048f6f3-e39b-4d79-9cd8-d4489d2a0607 # Charity Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d276fc8-4d6d-4c69-9ef7-194b21c2c012
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1559430-0156-4cee-a03a-62d268d3f13c # Charity Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc8c5457-759e-4f3c-8e8c-1b3d15cc14bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0786060-d7cc-4bd7-bb27-a9b0fa4b4f5e # Charity Logo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87538089-778d-4cc7-a199-4b11f888e616
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e1ac859d-d8a2-4980-bbb3-736617a2dcc5
        userCondition: null
fields:
  3048f6f3-e39b-4d79-9cd8-d4489d2a0607: # Charity Name
    columnSuffix: tfnriifk
    contentColumnType: text
    fieldGroup: null
    handle: charityName
    instructions: null
    name: 'Charity Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c1559430-0156-4cee-a03a-62d268d3f13c: # Charity Text
    columnSuffix: utbtgvea
    contentColumnType: text
    fieldGroup: null
    handle: charityText
    instructions: null
    name: 'Charity Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e0786060-d7cc-4bd7-bb27-a9b0fa4b4f5e: # Charity Logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: charityLogo
    instructions: null
    name: 'Charity Logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: charity
name: Charity
sortOrder: 1
