field: 62f35c23-97f2-4a5e-b4a3-d2b64ce080b7 # Other Products
fieldLayouts:
  9303c8bd-38c0-4e4c-a27b-d0392a108db6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e31a8132-1a54-495c-b2ae-dd014ceb5312 # Other Product Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a2a18e8-4274-4c70-b338-d8551f0cfcb1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06989989-0582-4eea-8228-ca10e50ee8dc # Product Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d650b282-3681-4f88-a309-8adaa9214bbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0bb27833-084b-462a-b804-3dd8ee588b44 # Product Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9824a50a-583f-41d0-b7d4-b38a4ec2b9ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07d48225-8339-4a81-a08a-d5ea6a943bf7
        userCondition: null
fields:
  0bb27833-084b-462a-b804-3dd8ee588b44: # Product Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: productLink
    instructions: null
    name: 'Product Link'
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  06989989-0582-4eea-8228-ca10e50ee8dc: # Product Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: productImage
    instructions: null
    name: 'Product Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:30f565ed-7240-4efe-a184-fc54e0316ce7' # Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e31a8132-1a54-495c-b2ae-dd014ceb5312: # Other Product Title
    columnSuffix: cabulndd
    contentColumnType: text
    fieldGroup: null
    handle: otherProductTitle
    instructions: null
    name: 'Other Product Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: otherProduct
name: 'Other Product'
sortOrder: 1
