fieldLayouts:
  46a3fcce-383c-46b4-91ea-d4a3afc6b6e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a78b4cc7-06a7-42b4-942f-e9537fd9c42a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb66b71d-ada6-4350-ae6c-d7e96f14cb82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2debc66f-1d6a-4a9e-9bc6-652438bff342
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b750ab5a-460e-404f-9c02-0dd2773cf18c # Sub-Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b3cb1f0-24f3-45fb-8124-a471b4870e48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9dd9737-938d-45e4-8827-0d109b42b6db
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 1d3b626c-377e-4ee4-83dc-cd5a7f3b36ed
        userCondition: null
handle: aboutUs
hasTitleField: false
name: 'About Us'
section: 258eb096-759c-4203-be41-eb0e87d51184 # About Us
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
