fieldLayouts:
  6cf42ca0-55a1-4406-b454-cb30b2d879b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c4e5a32-151d-45d9-95d0-d8d1a57003ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff5d7f7a-2909-431e-8dd5-2b87def999d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4802d4c-e716-4786-bf52-11a4de0e3fb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a9d9b0b-4b02-42d1-a3a1-a98372ea9640
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: e90e6313-f01f-41fd-8a03-9a9c8cad0301
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 19bec4ec-4999-4efe-8cfc-3bb6ab779bf6 # Products
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7455f78c-7700-45a8-9229-5046452a5461
            userCondition: null
            warning: null
            width: 100
        name: Products
        uid: 70cbd938-4af0-48a7-a145-907cc8069f7d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b9491886-e188-4793-a4d1-bc152e156413 # Featured Service Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4cb0e72-835d-437a-9c78-a1a79bec95e4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fb9844f8-ed04-4183-9774-aed148fe9ca9 # Featured Service Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14cc5c2e-adb5-4696-bc56-e7cc998a01e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc104013-5f50-42dc-ae33-8936c27e3310 # Featured Service Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19b15581-dafd-455a-9817-5deba567a1a7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6860d189-127f-47f4-b4db-78acd881d3a9 # Featured Service Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfa2b5b4-ee23-4eb7-9a75-47d8ab40c710
            userCondition: null
            warning: null
            width: 100
        name: 'Featured Service'
        uid: ae95f4e0-6c16-47a9-87e0-7bf563e431f7
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: b5be2983-4df9-4ff7-82ee-6d496fc7b647 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
