fieldLayouts:
  6cf42ca0-55a1-4406-b454-cb30b2d879b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4c4e5a32-151d-45d9-95d0-d8d1a57003ee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff5d7f7a-2909-431e-8dd5-2b87def999d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4802d4c-e716-4786-bf52-11a4de0e3fb3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e90e6313-f01f-41fd-8a03-9a9c8cad0301
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: b5be2983-4df9-4ff7-82ee-6d496fc7b647 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
