fieldLayouts:
  deafa4a7-8249-4d18-aec9-4096eca328ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5d0ee411-efdb-4f77-81cf-3df10a31709a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7be745c-1cb0-48d0-85a0-04881893b739
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4628284d-ffc5-4b60-a794-cbf2c9757925
        userCondition: null
handle: humanRights
hasTitleField: false
name: 'Human Rights'
section: 558ee88c-497d-4af1-9d09-1c11c9537d88 # Human Rights
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
