fieldLayouts:
  f7d12f31-4704-4ce6-8d0a-7182d1d4478f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4e6ee219-13a1-4b05-9fc6-ea6312670197
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd979b8-748b-4ac5-82d1-ede11e5a66f3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e71db4d3-58ea-4885-a914-b13809db7eb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b750ab5a-460e-404f-9c02-0dd2773cf18c # Sub-Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e82a5fca-2dab-4645-a78c-68bced08f510
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed4b2eb4-6cca-4c43-9f7a-96c070a9a9cd # Sub-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bc9b0276-76cf-42a3-9779-3100b22215dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9beb320e-55ff-4276-8d64-7bfbe81ffa88 # Sub-Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee49be32-fc06-484f-a8e3-f97712302cbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb444a68-c4f6-4584-a1e2-75e2a4919659
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62f35c23-97f2-4a5e-b4a3-d2b64ce080b7 # Other Products
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0912ed41-c6ee-49d5-89ae-fb879c6f05f1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26d6d0e7-ae2a-47e5-bde4-14ce422767e8
        userCondition: null
handle: organic
hasTitleField: false
name: Organic
section: c33509c8-d402-4a59-a44e-ca5826d54f07 # Organic
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
