fieldLayouts:
  0e0bed69-17b6-4349-b57c-7f056eb019ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f619c718-7c76-436e-93ac-c395b0beb52b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9a5d644-3cf7-41af-b2fb-8f846de6634a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4224f95-c227-4302-af2b-8748c69a348d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b750ab5a-460e-404f-9c02-0dd2773cf18c # Sub-Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aad7ad84-8f0b-40d7-83d4-23946bf24eb9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26fec63f-1869-4541-b215-f3d4ec41ff30
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9fc6cf10-93f5-48a9-abcc-6864ab4188b7
        userCondition: null
handle: portsStorage
hasTitleField: false
name: 'Ports & Storage'
section: e5e32361-cb97-4a12-9f07-6bf20deb6dea # Ports & Storage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
