fieldLayouts:
  babc9ecc-dd5f-40be-816e-308dfe39be36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6644ee49-e1b0-46d3-b02d-a0269cab37c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7147f6b1-0a91-4d87-81ab-76a972ce37fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 348e185d-b316-4ccb-999c-49445b886346 # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fb591c7-aa5f-468b-ba87-8a9162479745
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63bb3a47-12a0-42df-ad76-aada0e7e4300
        userCondition: null
handle: privacy
hasTitleField: false
name: Privacy
section: c6e4011e-b602-4262-ba06-049b96abb697 # Privacy
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
