fieldLayouts:
  a7b8c2f1-a52b-4041-9073-6b1d6adf533a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 64ab1c1c-7fd6-4e51-bb47-d33bc92f546d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72743e88-3dd3-478e-83b3-747a3bb41bf1 # Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a66c8bc7-3d51-4492-ae00-7733a2a8e9a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 959c8c36-64ab-4b18-80e1-cec06be400a7 # Hero Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 752f8983-8ead-4d25-aa5d-0a0f1871da3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 89cb94de-d037-45a9-a71f-0aab6e10c656
        userCondition: null
handle: thanks
hasTitleField: false
name: Thanks
section: 1ed059c1-ed1f-4a72-a56e-63058d7c494a # Thanks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
