columnSuffix: pgjwoxcr
contentColumnType: string(440)
fieldGroup: bd6f2a96-c03a-4fc3-9bee-4f392ccab890 # Home Page
handle: featuredServiceDescription
instructions: null
name: 'Featured Service Description'
searchable: false
settings:
  byteLimit: null
  charLimit: 110
  code: false
  columnType: null
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
