columnSuffix: svapwxkb
contentColumnType: text
fieldGroup: bd6f2a96-c03a-4fc3-9bee-4f392ccab890 # Home Page
handle: featuredServiceTitle
instructions: null
name: 'Featured Service Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
