columnSuffix: null
contentColumnType: string
fieldGroup: dfd55486-848c-47c3-b7f3-a06bfac39166 # Header
handle: productLinks
instructions: null
name: 'Product Links'
searchable: false
settings:
  contentTable: '{{%matrixcontent_productlinks}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
