dateModified: 1693837353
email:
  fromEmail: clare_spafford@andersonsinc.com
  fromName: 'Feed Factors'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageUpload:
    hasUrls: true
    name: 'Image Upload'
    settings:
      path: '@assetBasePath'
    type: craft\fs\Local
    url: '@assetBaseUrl'
meta:
  __names__:
    1c2d9731-7ee9-4411-be83-15a962a4f4a6: 'Product Link' # Product Link
    19bec4ec-4999-4efe-8cfc-3bb6ab779bf6: Products # Products
    30f565ed-7240-4efe-a184-fc54e0316ce7: Uploads # Uploads
    45b6a722-0451-438d-a395-e48fbd911ee9: Common # Common
    77db26de-4493-41b3-92f3-cbe2f057c743: Photo # Photo
    348e185d-b316-4ccb-999c-49445b886346: 'Hero Text' # Hero Text
    477a4ab6-dd0b-4ae4-ab1c-705ca7427a31: Hero # Hero
    554cf4a0-139a-46bd-beda-53682ebb6be9: Home # Home
    959c8c36-64ab-4b18-80e1-cec06be400a7: 'Hero Title' # Hero Title
    5295d6da-5ed9-4a07-9721-ff6c8cc061b2: 'Feed Factors' # Feed Factors
    6860d189-127f-47f4-b4db-78acd881d3a9: 'Featured Service Link' # Featured Service Link
    72743e88-3dd3-478e-83b3-747a3bb41bf1: 'Hero Image' # Hero Image
    b5be2983-4df9-4ff7-82ee-6d496fc7b647: Home # Home
    b8a881c8-6719-43ae-a610-5a8990bbbd66: 'Product Title' # Product Title
    b9491886-e188-4793-a4d1-bc152e156413: 'Featured Service Background Image' # Featured Service Background Image
    bd6f2a96-c03a-4fc3-9bee-4f392ccab890: 'Home Page' # Home Page
    c5ccd1eb-d4c5-401b-a958-2c64259f9057: Product # Product
    c9645a14-4d5e-4c62-9d67-baf0e20668d6: 'Product Card Image' # Product Card Image
    cc104013-5f50-42dc-ae33-8936c27e3310: 'Featured Service Description' # Featured Service Description
    e3da11a7-21f1-440d-90b8-dd8047d36901: 'Featured Service' # Featured Service
    e76438ef-4ed0-454e-8c51-99d377b2e4bf: 'Feed Factors' # Feed Factors
    ec4a4386-ade3-42d7-8a23-e2b919627f86: Description # Description
    fb9844f8-ed04-4183-9774-aed148fe9ca9: 'Featured Service Title' # Featured Service Title
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Feed Factors'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
