dateModified: 1694176398
email:
  fromEmail: clare_spafford@andersonsinc.com
  fromName: 'Feed Factors'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageUpload:
    hasUrls: true
    name: 'Image Upload'
    settings:
      path: '@assetBasePath'
    type: craft\fs\Local
    url: '@assetBaseUrl'
meta:
  __names__:
    0a372a17-7f19-44ae-a401-23ea3d202698: 'Pet Food' # Pet Food
    1bf5e238-6311-4cf4-991e-fc78ffa3f1f2: 'Contact Us' # Contact Us
    1c2d9731-7ee9-4411-be83-15a962a4f4a6: 'Product Link' # Product Link
    3d349985-7a46-402b-88f3-ecad9ea175ca: Phone # Phone
    5d06ebed-5a1c-465b-9ae0-bed5d9adfc6c: 'Non GM & Animal Feed' # Non GM & Animal Feed
    6e5eb59d-53e4-41b2-8a4d-f55f440ce102: 'Link Destination' # Link Destination
    8bdd2fe3-231a-4800-9366-938ad4f55b17: 'Awards and Accolades' # Awards and Accolades
    19bec4ec-4999-4efe-8cfc-3bb6ab779bf6: Products # Products
    22e90156-5efa-4274-974e-05735a0d4496: 'Ports & Storage' # Ports & Storage
    30f565ed-7240-4efe-a184-fc54e0316ce7: Uploads # Uploads
    32ae9651-c036-48a8-b929-d86988ffd8ca: Link # Link
    34f5e818-2d2b-4eba-8f40-35abc9466544: 'Link Destination' # Link Destination
    45b6a722-0451-438d-a395-e48fbd911ee9: Common # Common
    045e1375-baca-43e0-bc7d-aafb3528b5df: 'Contact Us' # Contact Us
    48f73b93-d2e4-47e8-a341-c5535cf1e3d3: 'Nav Links' # Nav Links
    49be7a3a-8951-44e7-a4af-72d91710d950: 'Product Links' # Product Links
    77db26de-4493-41b3-92f3-cbe2f057c743: Photo # Photo
    85e835c3-278b-489b-93cb-6f2f07650688: 'Product Link' # Product Link
    258eb096-759c-4203-be41-eb0e87d51184: 'About Us' # About Us
    348e185d-b316-4ccb-999c-49445b886346: 'Hero Text' # Hero Text
    477a4ab6-dd0b-4ae4-ab1c-705ca7427a31: Hero # Hero
    538e77bf-23bd-480e-80fa-e49b424ef3bb: 'Pet Food' # Pet Food
    554cf4a0-139a-46bd-beda-53682ebb6be9: Home # Home
    826d2f1e-89e7-4d35-b602-014fd7478839: 'Link Text' # Link Text
    959c8c36-64ab-4b18-80e1-cec06be400a7: 'Hero Title' # Hero Title
    1512a705-46ac-4ba2-a263-7358b242643f: Email # Email
    5295d6da-5ed9-4a07-9721-ff6c8cc061b2: 'Feed Factors' # Feed Factors
    6860d189-127f-47f4-b4db-78acd881d3a9: 'Featured Service Link' # Featured Service Link
    72743e88-3dd3-478e-83b3-747a3bb41bf1: 'Hero Image' # Hero Image
    58799525-d9b5-4e70-ac6d-c343f77507a1: Organic # Organic
    a5320ca1-a946-4261-91c8-9ae7620d5418: 'Non GM & Animal Feed' # Non GM & Animal Feed
    b2bfedd2-94f0-42d6-957a-61849e3979ac: 'Awards and Accolades' # Awards and Accolades
    b5be2983-4df9-4ff7-82ee-6d496fc7b647: Home # Home
    b8a881c8-6719-43ae-a610-5a8990bbbd66: 'Product Title' # Product Title
    b9491886-e188-4793-a4d1-bc152e156413: 'Featured Service Background Image' # Featured Service Background Image
    bd6f2a96-c03a-4fc3-9bee-4f392ccab890: 'Home Page' # Home Page
    c5ccd1eb-d4c5-401b-a958-2c64259f9057: Product # Product
    c9645a14-4d5e-4c62-9d67-baf0e20668d6: 'Product Card Image' # Product Card Image
    c33509c8-d402-4a59-a44e-ca5826d54f07: Organic # Organic
    cc104013-5f50-42dc-ae33-8936c27e3310: 'Featured Service Description' # Featured Service Description
    cd68ad67-aeec-41d5-83be-368e122a3542: 'Link Text' # Link Text
    d6b238cc-0b1f-4f87-bcaa-8de31aa4717a: Header # Header
    d57ed528-cda8-49f4-bfac-571fc62e4317: 'About Us' # About Us
    dfd55486-848c-47c3-b7f3-a06bfac39166: Header # Header
    e3da11a7-21f1-440d-90b8-dd8047d36901: 'Featured Service' # Featured Service
    e5e32361-cb97-4a12-9f07-6bf20deb6dea: 'Ports & Storage' # Ports & Storage
    e76438ef-4ed0-454e-8c51-99d377b2e4bf: 'Feed Factors' # Feed Factors
    ec4a4386-ade3-42d7-8a23-e2b919627f86: Description # Description
    fb9844f8-ed04-4183-9774-aed148fe9ca9: 'Featured Service Title' # Featured Service Title
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: 'Feed Factors'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
