fieldLayouts:
  87f72317-be7b-4b6b-a1f3-09d962e620c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 48f73b93-d2e4-47e8-a341-c5535cf1e3d3 # Nav Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb1b7723-a294-4009-a062-c4abeaf59f80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49be7a3a-8951-44e7-a4af-72d91710d950 # Product Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6f0db9b-0328-49f9-ae7f-73dcab7c6339
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e12a2cc-05eb-425e-8e8a-04387e69f232
        userCondition: null
handle: header
name: Header
sortOrder: 1
