defaultPlacement: end
enableVersioning: true
handle: petFood
name: 'Pet Food'
propagationMethod: all
siteSettings:
  5295d6da-5ed9-4a07-9721-ff6c8cc061b2: # Feed Factors
    enabledByDefault: true
    hasUrls: true
    template: pet-food.twig
    uriFormat: pet-food
type: single
