defaultPlacement: end
enableVersioning: true
handle: termsOfUse
name: 'Terms of Use'
propagationMethod: all
siteSettings:
  5295d6da-5ed9-4a07-9721-ff6c8cc061b2: # Feed Factors
    enabledByDefault: true
    hasUrls: true
    template: terms-of-use.twig
    uriFormat: terms-of-use
type: single
